version: '3.7'
services:
  server1:
    container_name: server1
    build: .
    image: server
    links:
      - mysql
    depends_on:
      - mysql
    env_file:
      - .env
  server2:
    container_name: server2
    build: .
    links:
      - mysql
    depends_on:
      - mysql
    env_file:
      - .env


  mysql:
    container_name: mysql
    env_file:
      - .env
    image: mysql
    expose:
      # Opens port 3306 on the container
      - '3306'

  migrator:
    image: server:latest
    env_file:
      - .env
    links:
      - mysql
    depends_on:
      - mysql
    command: ["./wait-for-it/wait-for-it.sh", "mysql:3306", "--", "npm", "run", "migrate"]

  nginx:
    build: ./nginx
    tty: true
    links:
      - server1
      - server2
    depends_on:
      - server1
      - server2
    ports:
        - '8080:8080'